apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec:
      containers:
      - name: food-app
        image: pravallika1015/food-app:pravallika
        ports:
        - containerPort: 5000
